#!/usr/bin/env bash

# Script to set environment variables for AirBnB_Clone_v3 project
# Usage: source hbnb_env

export HBNB_ENV=test
export HBNB_MYSQL_USER=hbnb_test
export HBNB_MYSQL_PWD=hbnb_test_pwd
export HBNB_MYSQL_HOST=localhost
export HBNB_MYSQL_DB=hbnb_test_db
export HBNB_TYPE_STORAGE=db

# Set Python path
export PYTHONPATH=`(pwd)`
